// SPDX-License-Identifier: Apache-2.0
/**
 * @file   qat_lora_mnist_digit_split_poc.cpp
 * @brief  POC: Proper digit-split experiment — train base on digits 0-7,
 *         then fine-tune LoRA to learn digits 8-9.
 *
 * This is the "proper" transfer-learning experiment that mirrors the real
 * Qwen3 scenario:
 *   - The base model is pre-trained on a SUBSET of classes (digits 0-7)
 *   - It is quantized to Q6_K and frozen
 *   - LoRA adapters are fine-tuned to handle ALL 10 digits
 *   - We evaluate on all digits AND separately on digits 8-9
 *
 * Required dataset files (generated by create_digit_split_mnist.py):
 *   - mnist_digits_0to7.dat   (~48k samples, digits 0-7 only)
 *   - mnist_all_digits.dat    (60k samples, all digits)
 *
 * Architecture: 768→256→256→256→10  (same as main POC)
 */

#include <algorithm>
#include <cmath>
#include <cstring>
#include <fstream>
#include <iomanip>
#include <iostream>
#include <memory>
#include <numeric>
#include <random>
#include <vector>

#include <app_context.h>
#include <dataset.h>
#include <engine.h>
#include <layer.h>
#include <model.h>
#include <optimizer.h>
#include <quantizer.h>
#include <tensor.h>
#include <tensor_dim.h>

#include "qat_fc_layer.h"

using namespace ml::train;
using namespace nntrainer;

// ─── Network & Training Config ──────────────────────────────────────────────

static constexpr unsigned int FEATURE_SIZE_ORIG = 784;
static constexpr unsigned int FEATURE_SIZE = 768;  // truncated for Q6_K compat
static constexpr unsigned int HIDDEN_DIM = 256;
static constexpr unsigned int NUM_CLASSES = 10;

static constexpr unsigned int BATCH_SIZE = 1;
static constexpr unsigned int EPOCHS_FP32 = 5;
static constexpr unsigned int EPOCHS_LORA = 10;  // more epochs since LoRA has to learn new digits
static constexpr unsigned int LORA_RANK = 4;
constexpr unsigned int SEED = 42;

// ─── MNIST Data Loading ─────────────────────────────────────────────────────

class DataInformation {
public:
  DataInformation(unsigned int num_samples, const std::string &filename,
                  unsigned int offset = 0);
  unsigned int count;
  unsigned int num_samples;
  unsigned int sample_offset;
  std::ifstream file;
  std::vector<unsigned int> idxes;
  std::mt19937 rng;
};

DataInformation::DataInformation(unsigned int num_samples,
                                 const std::string &filename,
                                 unsigned int offset) :
  count(0), num_samples(num_samples), sample_offset(offset),
  file(filename, std::ios::in | std::ios::binary),
  idxes(num_samples) {
  std::iota(idxes.begin(), idxes.end(), offset);
  rng.seed(SEED);
  std::shuffle(idxes.begin(), idxes.end(), rng);
  if (!file.good())
    throw std::invalid_argument("Cannot open: " + filename);
}

static bool getData(std::ifstream &F, float *input, float *label,
                    unsigned int id) {
  F.clear();
  F.seekg(0, std::ios_base::end);
  uint64_t file_length = F.tellg();
  uint64_t position = (uint64_t)((FEATURE_SIZE_ORIG + NUM_CLASSES) *
                                 (uint64_t)id * sizeof(float));
  if (position > file_length) return false;
  F.seekg(position, std::ios::beg);

  std::vector<float> tmp(FEATURE_SIZE_ORIG);
  F.read((char *)tmp.data(), sizeof(float) * FEATURE_SIZE_ORIG);
  for (unsigned int i = 0; i < FEATURE_SIZE; i++) {
    input[i] = tmp[i] / 255.0f;
  }

  F.read((char *)label, sizeof(float) * NUM_CLASSES);
  return true;
}

static int getSample_train(float **outVec, float **outLabel, bool *last,
                           void *user_data) {
  auto data = reinterpret_cast<DataInformation *>(user_data);
  getData(data->file, *outVec, *outLabel, data->idxes.at(data->count));
  data->count++;
  if (data->count < data->num_samples) {
    *last = false;
  } else {
    *last = true;
    data->count = 0;
    std::shuffle(data->idxes.begin(), data->idxes.end(), data->rng);
  }
  return 0;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

struct LayerWeights {
  std::string name;
  std::vector<float> weight;
  std::vector<float> bias;
  unsigned int in_dim;
  unsigned int out_dim;
};

static LayerWeights extractLayer(std::unique_ptr<Model> &model,
                                 const char *name,
                                 unsigned int in_d, unsigned int out_d) {
  LayerWeights lw;
  lw.name = name;
  lw.in_dim = in_d;
  lw.out_dim = out_d;

  std::shared_ptr<ml::train::Layer> layer;
  model->getLayer(name, &layer);
  std::vector<float *> wptrs;
  std::vector<TensorDim> wdims;
  layer->getWeights(wptrs, wdims);

  if (wptrs.size() >= 1 && wdims.size() >= 1) {
    size_t wsz = 1;
    for (unsigned d = 0; d < wdims[0].getNumDim(); ++d)
      wsz *= wdims[0].getDim()[d];
    lw.weight.assign(wptrs[0], wptrs[0] + wsz);
  }
  if (wptrs.size() >= 2 && wdims.size() >= 2) {
    size_t bsz = 1;
    for (unsigned d = 0; d < wdims[1].getNumDim(); ++d)
      bsz *= wdims[1].getDim()[d];
    lw.bias.assign(wptrs[1], wptrs[1] + bsz);
  }
  return lw;
}

static Tensor makeWeightTensor(const LayerWeights &lw) {
  Tensor t(TensorDim(1, 1, lw.in_dim, lw.out_dim));
  std::memcpy(t.getData<float>(), lw.weight.data(), lw.weight.size() * sizeof(float));
  return t;
}

static Tensor makeBiasTensor(const LayerWeights &lw) {
  Tensor t(TensorDim(1, 1, 1, lw.out_dim));
  std::memcpy(t.getData<float>(), lw.bias.data(), lw.bias.size() * sizeof(float));
  return t;
}

// ─── Manual forward pass ────────────────────────────────────────────────────

static void forward_pass(const Tensor &input,
                          const Tensor &W1, const Tensor &b1,
                          const Tensor &W2, const Tensor &b2,
                          const Tensor &W3, const Tensor &b3,
                          const Tensor &Wout, const Tensor &bout,
                          Tensor &logits) {
  unsigned int batch = input.getDim().batch();

  Tensor h1(TensorDim(batch, 1, 1, HIDDEN_DIM));
  input.dot(W1, h1, false, false);
  h1.add_i(b1);
  h1.apply<float>([](float v) { return v > 0.f ? v : 0.f; }, h1);

  Tensor h2(TensorDim(batch, 1, 1, HIDDEN_DIM));
  h1.dot(W2, h2, false, false);
  h2.add_i(b2);
  h2.apply<float>([](float v) { return v > 0.f ? v : 0.f; }, h2);

  Tensor h3(TensorDim(batch, 1, 1, HIDDEN_DIM));
  h2.dot(W3, h3, false, false);
  h3.add_i(b3);
  h3.apply<float>([](float v) { return v > 0.f ? v : 0.f; }, h3);

  h3.dot(Wout, logits, false, false);
  logits.add_i(bout);
}

// ─── Accuracy evaluation ────────────────────────────────────────────────────

static float evaluateAccuracy(const std::string &data_file,
                               const Tensor &W1, const Tensor &b1,
                               const Tensor &W2, const Tensor &b2,
                               const Tensor &W3, const Tensor &b3,
                               const Tensor &Wout, const Tensor &bout,
                               unsigned int test_offset,
                               unsigned int num_test) {
  unsigned int correct = 0;
  unsigned int total = 0;

  std::ifstream file(data_file, std::ios::in | std::ios::binary);
  std::vector<float> input_buf(FEATURE_SIZE);
  std::vector<float> label_buf(NUM_CLASSES);

  for (unsigned int i = 0; i < num_test; ++i) {
    if (!getData(file, input_buf.data(), label_buf.data(), test_offset + i))
      break;

    Tensor input(TensorDim(1, 1, 1, FEATURE_SIZE));
    std::memcpy(input.getData<float>(), input_buf.data(),
                FEATURE_SIZE * sizeof(float));

    Tensor logits(TensorDim(1, 1, 1, NUM_CLASSES));
    forward_pass(input, W1, b1, W2, b2, W3, b3, Wout, bout, logits);

    const float *lp = logits.getData<float>();
    int pred = 0;
    for (unsigned j = 1; j < NUM_CLASSES; ++j)
      if (lp[j] > lp[pred]) pred = j;

    int truth = 0;
    for (unsigned j = 1; j < NUM_CLASSES; ++j)
      if (label_buf[j] > label_buf[truth]) truth = j;

    if (pred == truth) correct++;
    total++;
  }

  return total > 0 ? (float)correct / total * 100.0f : 0.0f;
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 1: Train FP32 baseline on digits 0-7 ONLY
// ═════════════════════════════════════════════════════════════════════════════

static std::vector<LayerWeights> trainFP32_digits07(
    const std::string &data_file_07,
    unsigned int num_train_07, unsigned int num_val_07) {
  std::cerr << "\n╔══════════════════════════════════════════════╗"
            << "\n║  Phase 1: FP32 Training on DIGITS 0-7 ONLY  ║"
            << "\n╚══════════════════════════════════════════════╝"
            << std::endl;

  // Use 80/20 split within the 0-7 dataset
  auto train_data = std::make_unique<DataInformation>(num_train_07, data_file_07, 0);
  auto val_data = std::make_unique<DataInformation>(num_val_07, data_file_07, num_train_07);

  std::shared_ptr<ml::train::Dataset> dataset_train =
    createDataset(DatasetType::GENERATOR, getSample_train, train_data.get());
  std::shared_ptr<ml::train::Dataset> dataset_val =
    createDataset(DatasetType::GENERATOR, getSample_train, val_data.get());

  auto model = createModel(ModelType::NEURAL_NET,
                           {"batch_size=" + std::to_string(BATCH_SIZE)});

  model->addLayer(createLayer("input", {"name=input0",
                  "input_shape=1:1:" + std::to_string(FEATURE_SIZE)}));
  model->addLayer(createLayer("fully_connected", {"name=fc1",
                  "unit=" + std::to_string(HIDDEN_DIM)}));
  model->addLayer(createLayer("activation", {"name=relu1", "activation=relu"}));
  model->addLayer(createLayer("fully_connected", {"name=fc2",
                  "unit=" + std::to_string(HIDDEN_DIM)}));
  model->addLayer(createLayer("activation", {"name=relu2", "activation=relu"}));
  model->addLayer(createLayer("fully_connected", {"name=fc3",
                  "unit=" + std::to_string(HIDDEN_DIM)}));
  model->addLayer(createLayer("activation", {"name=relu3", "activation=relu"}));
  model->addLayer(createLayer("fully_connected",
                  {"name=output", "unit=" + std::to_string(NUM_CLASSES), "activation=softmax"}));

  auto optimizer = createOptimizer("sgd", {"learning_rate=0.001"});
  model->setOptimizer(std::move(optimizer));
  model->setProperty({"epochs=" + std::to_string(EPOCHS_FP32), "loss=cross"});

  model->compile();
  model->initialize();
  model->setDataset(DatasetModeType::MODE_TRAIN, dataset_train);
  model->setDataset(DatasetModeType::MODE_VALID, dataset_val);

  model->train();
  std::cerr << "FP32 training loss: " << model->getTrainingLoss() << std::endl;

  std::cerr << "Extracting FP32 weights..." << std::endl;
  std::vector<LayerWeights> mw;
  mw.push_back(extractLayer(model, "fc1", FEATURE_SIZE, HIDDEN_DIM));
  mw.push_back(extractLayer(model, "fc2", HIDDEN_DIM, HIDDEN_DIM));
  mw.push_back(extractLayer(model, "fc3", HIDDEN_DIM, HIDDEN_DIM));
  mw.push_back(extractLayer(model, "output", HIDDEN_DIM, NUM_CLASSES));
  return mw;
}

// ═════════════════════════════════════════════════════════════════════════════
// Phase 2: Quantize + LoRA-QAT on ALL digits (0-9)
// ═════════════════════════════════════════════════════════════════════════════
// The base model was ONLY trained on digits 0-7.
// LoRA must now learn to handle digits 8 and 9 as well.

static void trainLoRAQAT_allDigits(
    const std::string &data_file_all,
    const std::vector<LayerWeights> &fp32_weights,
    unsigned int finetune_offset,
    unsigned int finetune_train,
    unsigned int finetune_val,
    unsigned int test_offset_all,
    unsigned int num_test_all,
    const std::string &data_file_89,
    unsigned int num_test_89) {

  std::cerr << "\n╔══════════════════════════════════════════════╗"
            << "\n║  Phase 2: Q6_K Base (0-7) + LoRA on ALL     ║"
            << "\n╚══════════════════════════════════════════════╝"
            << std::endl;

  // ── Step 2a: Quantize base weights to Q6_K ──

  std::cerr << "\n--- Step 2a: Quantizing base weights to Q6_K ---" << std::endl;

  auto q6k_quantizer = Quantization::createQuantizer(QScheme::Q6_K);

  Tensor W1_fp32 = makeWeightTensor(fp32_weights[0]);
  Tensor W2_fp32 = makeWeightTensor(fp32_weights[1]);
  Tensor W3_fp32 = makeWeightTensor(fp32_weights[2]);

  Tensor W1_q6k = q6k_quantizer->quantize(W1_fp32, Tdatatype::Q6_K);
  Tensor W2_q6k = q6k_quantizer->quantize(W2_fp32, Tdatatype::Q6_K);
  Tensor W3_q6k = q6k_quantizer->quantize(W3_fp32, Tdatatype::Q6_K);

  std::cerr << "  Quantized to Q6_K" << std::endl;

  // ── Step 2b: Evaluate Q6_K base on ALL digits (should be poor on 8,9) ──

  Tensor b1 = makeBiasTensor(fp32_weights[0]);
  Tensor b2 = makeBiasTensor(fp32_weights[1]);
  Tensor b3 = makeBiasTensor(fp32_weights[2]);
  Tensor Wout = makeWeightTensor(fp32_weights[3]);
  Tensor bout = makeBiasTensor(fp32_weights[3]);

  std::cerr << "\n--- Step 2b: Evaluating Q6_K base (trained on 0-7 only) ---" << std::endl;

  float q6k_all_acc = evaluateAccuracy(data_file_all,
    W1_q6k, b1, W2_q6k, b2, W3_q6k, b3, Wout, bout,
    test_offset_all, num_test_all);
  std::cerr << "  Q6_K accuracy on ALL digits: " << q6k_all_acc << "%" << std::endl;

  float q6k_89_acc = evaluateAccuracy(data_file_89,
    W1_q6k, b1, W2_q6k, b2, W3_q6k, b3, Wout, bout,
    0, num_test_89);
  std::cerr << "  Q6_K accuracy on digits 8-9 ONLY: " << q6k_89_acc
            << "% (expected very poor — model never saw these!)" << std::endl;

  // ── Step 2c: Build LoRA-QAT model ──

  std::cerr << "\n--- Step 2c: Building LoRA-QAT model ---" << std::endl;

  auto train_data = std::make_unique<DataInformation>(finetune_train, data_file_all, finetune_offset);
  auto val_data = std::make_unique<DataInformation>(finetune_val, data_file_all, finetune_offset + finetune_train);
  std::shared_ptr<ml::train::Dataset> dataset_train =
    createDataset(DatasetType::GENERATOR, getSample_train, train_data.get());
  std::shared_ptr<ml::train::Dataset> dataset_val =
    createDataset(DatasetType::GENERATOR, getSample_train, val_data.get());

  auto lora_model = createModel(ModelType::NEURAL_NET,
                           {"batch_size=" + std::to_string(BATCH_SIZE)});

  lora_model->addLayer(createLayer("input", {"name=input0",
                  "input_shape=1:1:" + std::to_string(FEATURE_SIZE)}));

  lora_model->addLayer(createLayer("qat_fully_connected", {"name=lfc1",
                  "unit=" + std::to_string(HIDDEN_DIM),
                  "lora_rank=" + std::to_string(LORA_RANK)}));
  lora_model->addLayer(createLayer("activation", {"name=relu1", "activation=relu"}));

  lora_model->addLayer(createLayer("qat_fully_connected", {"name=lfc2",
                  "unit=" + std::to_string(HIDDEN_DIM),
                  "lora_rank=" + std::to_string(LORA_RANK)}));
  lora_model->addLayer(createLayer("activation", {"name=relu2", "activation=relu"}));

  lora_model->addLayer(createLayer("qat_fully_connected", {"name=lfc3",
                  "unit=" + std::to_string(HIDDEN_DIM),
                  "lora_rank=" + std::to_string(LORA_RANK)}));
  lora_model->addLayer(createLayer("activation", {"name=relu3", "activation=relu"}));

  // Output layer: TRAINABLE — LoRA needs to learn new output logits for 8,9
  lora_model->addLayer(createLayer("fully_connected",
                  {"name=output", "unit=" + std::to_string(NUM_CLASSES),
                   "activation=softmax", "trainable=true"}));

  auto lora_optimizer = createOptimizer("adam", {"learning_rate=0.001"});
  lora_model->setOptimizer(std::move(lora_optimizer));
  lora_model->setProperty({"epochs=" + std::to_string(EPOCHS_LORA), "loss=cross"});

  lora_model->compile();
  lora_model->initialize();

  // ── Step 2d: Inject Q6_K weights ──

  std::cerr << "\n--- Step 2d: Injecting Q6_K weights ---" << std::endl;

  auto injectQ6K = [&](const char *name, Tensor &q6k_tensor) {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer(name, &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    std::memcpy(wptrs[0], q6k_tensor.getData<uint8_t>(), q6k_tensor.bytes());
  };

  injectQ6K("lfc1", W1_q6k);
  injectQ6K("lfc2", W2_q6k);
  injectQ6K("lfc3", W3_q6k);

  // Inject output layer weights and biases from QAT layers
  {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer("output", &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    if (wptrs.size() >= 1)
      std::memcpy(wptrs[0], fp32_weights[3].weight.data(),
                  fp32_weights[3].weight.size() * sizeof(float));
    if (wptrs.size() >= 2)
      std::memcpy(wptrs[1], fp32_weights[3].bias.data(),
                  fp32_weights[3].bias.size() * sizeof(float));
  }

  // Inject biases into LoRA layers
  auto injectBias = [&](const char *name, const LayerWeights &lw) {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer(name, &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    if (wptrs.size() >= 2 && !lw.bias.empty())
      std::memcpy(wptrs[1], lw.bias.data(), lw.bias.size() * sizeof(float));
  };

  injectBias("lfc1", fp32_weights[0]);
  injectBias("lfc2", fp32_weights[1]);
  injectBias("lfc3", fp32_weights[2]);

  std::cerr << "  Injected all weights" << std::endl;

  // ── Step 2e: Train LoRA on ALL digits ──

  lora_model->setDataset(DatasetModeType::MODE_TRAIN, dataset_train);
  lora_model->setDataset(DatasetModeType::MODE_VALID, dataset_val);

  std::cerr << "\n--- Step 2e: Training LoRA on ALL digits (0-9) ---" << std::endl;
  std::cerr << "  Base knows: digits 0-7 | LoRA must learn: digits 8-9" << std::endl;

  lora_model->train();

  // ── Step 2f: Evaluate after LoRA ──

  std::cerr << "\n--- Step 2f: Evaluating after LoRA-QAT ---" << std::endl;

  auto extractLoRA = [&](const char *name, unsigned int in_d, unsigned int out_d)
      -> std::pair<std::vector<float>, std::vector<float>> {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer(name, &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    std::vector<float> loraA_data, loraB_data;
    if (wptrs.size() >= 4) {
      loraA_data.assign(wptrs[2], wptrs[2] + in_d * LORA_RANK);
      loraB_data.assign(wptrs[3], wptrs[3] + LORA_RANK * out_d);
    }
    return {loraA_data, loraB_data};
  };

  auto computeEffective = [&](const Tensor &q6k_weight,
                               const std::vector<float> &loraA_data,
                               const std::vector<float> &loraB_data,
                               unsigned int in_d, unsigned int out_d) -> Tensor {
    Tensor dequant(TensorDim(1, 1, in_d, out_d));
    Tensor identity(TensorDim(1, 1, in_d, in_d));
    float *id_data = identity.getData<float>();
    std::memset(id_data, 0, in_d * in_d * sizeof(float));
    for (unsigned int i = 0; i < in_d; ++i)
      id_data[i * in_d + i] = 1.0f;
    identity.dot(q6k_weight, dequant, false, false);

    Tensor A(TensorDim(1, 1, in_d, LORA_RANK));
    std::memcpy(A.getData<float>(), loraA_data.data(), loraA_data.size() * sizeof(float));
    Tensor B(TensorDim(1, 1, LORA_RANK, out_d));
    std::memcpy(B.getData<float>(), loraB_data.data(), loraB_data.size() * sizeof(float));
    Tensor lora_contrib(TensorDim(1, 1, in_d, out_d));
    A.dot(B, lora_contrib, false, false);
    dequant.add_i(lora_contrib);
    return dequant;
  };

  auto [a1, b1l] = extractLoRA("lfc1", FEATURE_SIZE, HIDDEN_DIM);
  auto [a2, b2l] = extractLoRA("lfc2", HIDDEN_DIM, HIDDEN_DIM);
  auto [a3, b3l] = extractLoRA("lfc3", HIDDEN_DIM, HIDDEN_DIM);

  Tensor W1_eff = computeEffective(W1_q6k, a1, b1l, FEATURE_SIZE, HIDDEN_DIM);
  Tensor W2_eff = computeEffective(W2_q6k, a2, b2l, HIDDEN_DIM, HIDDEN_DIM);
  Tensor W3_eff = computeEffective(W3_q6k, a3, b3l, HIDDEN_DIM, HIDDEN_DIM);

  // Extract trained output + biases
  Tensor Wout_final(TensorDim(1, 1, HIDDEN_DIM, NUM_CLASSES));
  Tensor bout_final(TensorDim(1, 1, 1, NUM_CLASSES));
  {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer("output", &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    if (wptrs.size() >= 1)
      std::memcpy(Wout_final.getData<float>(), wptrs[0], HIDDEN_DIM * NUM_CLASSES * sizeof(float));
    if (wptrs.size() >= 2)
      std::memcpy(bout_final.getData<float>(), wptrs[1], NUM_CLASSES * sizeof(float));
  }

  auto extractBias = [&](const char *name, unsigned int out_d) -> Tensor {
    std::shared_ptr<ml::train::Layer> layer;
    lora_model->getLayer(name, &layer);
    std::vector<float *> wptrs;
    std::vector<TensorDim> wdims;
    layer->getWeights(wptrs, wdims);
    Tensor bias(TensorDim(1, 1, 1, out_d));
    if (wptrs.size() >= 2)
      std::memcpy(bias.getData<float>(), wptrs[1], out_d * sizeof(float));
    return bias;
  };

  Tensor b1_final = extractBias("lfc1", HIDDEN_DIM);
  Tensor b2_final = extractBias("lfc2", HIDDEN_DIM);
  Tensor b3_final = extractBias("lfc3", HIDDEN_DIM);

  // Evaluate on ALL digits
  float lora_all_acc = evaluateAccuracy(data_file_all,
    W1_eff, b1_final, W2_eff, b2_final, W3_eff, b3_final,
    Wout_final, bout_final,
    test_offset_all, num_test_all);
  std::cerr << "  LoRA-QAT accuracy on ALL digits:  " << lora_all_acc << "%" << std::endl;

  // Evaluate on digits 8-9 ONLY
  float lora_89_acc = evaluateAccuracy(data_file_89,
    W1_eff, b1_final, W2_eff, b2_final, W3_eff, b3_final,
    Wout_final, bout_final,
    0, num_test_89);
  std::cerr << "  LoRA-QAT accuracy on digits 8-9:  " << lora_89_acc << "%" << std::endl;

  // ── Summary ──
  std::cerr << "\n══════════════════════════════════════════════════"
            << "\n  DIGIT-SPLIT SUMMARY"
            << "\n══════════════════════════════════════════════════"
            << "\n  Q6_K base (trained 0-7) on ALL digits:     " << q6k_all_acc << "%"
            << "\n  Q6_K base (trained 0-7) on digits 8-9:     " << q6k_89_acc << "%"
            << "\n  LoRA-QAT (fine-tuned 0-9) on ALL digits:   " << lora_all_acc << "%"
            << "\n  LoRA-QAT (fine-tuned 0-9) on digits 8-9:   " << lora_89_acc << "%"
            << "\n══════════════════════════════════════════════════"
            << std::endl;

  if (lora_89_acc > q6k_89_acc + 5.0f) {
    std::cerr << "\n  ✓ SUCCESS: LoRA learned digits 8-9 that base model never saw!"
              << std::endl;
  }
}

// ═════════════════════════════════════════════════════════════════════════════
// Main
// ═════════════════════════════════════════════════════════════════════════════

int main(int argc, char *argv[]) {
  if (argc < 3) {
    std::cerr << "Usage: " << argv[0]
              << " <mnist_digits_0to7.dat> <mnist_all_digits.dat>"
              << " [mnist_digits_8to9.dat]"
              << std::endl;
    std::cerr << "\nGenerate these files using create_digit_split_mnist.py" << std::endl;
    return 1;
  }

  std::string data_07 = argv[1];
  std::string data_all = argv[2];
  std::string data_89 = (argc > 3) ? argv[3] : "";

  std::cerr << "\n══════════════════════════════════════════════════"
            << "\n  Digit-Split LoRA-QAT MNIST POC"
            << "\n  Base: trained on digits 0-7 only"
            << "\n  LoRA: fine-tuned to learn ALL digits (0-9)"
            << "\n══════════════════════════════════════════════════"
            << std::endl;

  // Register custom QAT layer
  auto &ct_engine = nntrainer::Engine::Global();
  auto app_context = static_cast<nntrainer::AppContext *>(
    ct_engine.getRegisteredContext("cpu"));
  try {
    app_context->registerFactory(
      nntrainer::createLayer<nntrainer::QATFullyConnectedLayer>);
  } catch (std::invalid_argument &) {}

  // Count samples in 0-7 file (each sample = (784+10) * 4 bytes)
  {
    std::ifstream f(data_07, std::ios::ate | std::ios::binary);
    if (!f.is_open()) {
      std::cerr << "Error: Cannot open file " << data_07 << std::endl;
      return 1;
    }
    size_t filesize = f.tellg();
    if (filesize < 0) {
      std::cerr << "Error: tellg() failed for " << data_07 << std::endl;
      return 1;
    }
    size_t sample_size = (FEATURE_SIZE_ORIG + NUM_CLASSES) * sizeof(float);
    unsigned int total_07 = filesize / sample_size;
    std::cerr << "\n  Digits 0-7 dataset: " << total_07 << " samples" << std::endl;

    unsigned int train_07 = (unsigned int)(total_07 * 0.8);
    unsigned int val_07 = total_07 - train_07;

    // Phase 1: Train on digits 0-7
    auto fp32_weights = trainFP32_digits07(data_07, train_07, val_07);

    // Count samples in all-digits file
    std::ifstream f_all(data_all, std::ios::ate | std::ios::binary);
    size_t filesize_all = f_all.tellg();
    unsigned int total_all = filesize_all / sample_size;
    std::cerr << "\n  All-digits dataset: " << total_all << " samples" << std::endl;

    // Use last 15000 for fine-tuning, last 5000 for test
    unsigned int test_count = 5000;
    unsigned int finetune_val_count = 3000;
    unsigned int finetune_train_count = 12000;
    unsigned int finetune_start = total_all - test_count - finetune_val_count - finetune_train_count;
    unsigned int test_start = total_all - test_count;

    // Count samples in 8-9 file
    unsigned int total_89 = 0;
    if (!data_89.empty()) {
      std::ifstream f89(data_89, std::ios::ate | std::ios::binary);
      total_89 = f89.tellg() / sample_size;
      std::cerr << "  Digits 8-9 dataset: " << total_89 << " samples" << std::endl;
    }

    // Evaluate FP32 base on all digits
    std::cerr << "\n--- Evaluating FP32 base (trained 0-7) on ALL digits ---" << std::endl;
    Tensor W1 = makeWeightTensor(fp32_weights[0]);
    Tensor b1 = makeBiasTensor(fp32_weights[0]);
    Tensor W2 = makeWeightTensor(fp32_weights[1]);
    Tensor b2 = makeBiasTensor(fp32_weights[1]);
    Tensor W3 = makeWeightTensor(fp32_weights[2]);
    Tensor b3 = makeBiasTensor(fp32_weights[2]);
    Tensor Wout = makeWeightTensor(fp32_weights[3]);
    Tensor bout = makeBiasTensor(fp32_weights[3]);

    float fp32_all = evaluateAccuracy(data_all, W1, b1, W2, b2, W3, b3, Wout, bout,
                                       test_start, test_count);
    std::cerr << "  FP32 accuracy on ALL digits: " << fp32_all << "%" << std::endl;

    if (!data_89.empty()) {
      float fp32_89 = evaluateAccuracy(data_89, W1, b1, W2, b2, W3, b3, Wout, bout,
                                        0, std::min(total_89, (unsigned int)2000));
      std::cerr << "  FP32 accuracy on digits 8-9: " << fp32_89 << "%" << std::endl;
    }

    // Phase 2: LoRA-QAT on all digits
    trainLoRAQAT_allDigits(data_all, fp32_weights,
                            finetune_start, finetune_train_count, finetune_val_count,
                            test_start, test_count,
                            data_89.empty() ? data_all : data_89,
                            data_89.empty() ? test_count : std::min(total_89, (unsigned int)2000));
  }

  std::cerr << "\n=== Done! Digit-Split POC Complete ===" << std::endl;
  return 0;
}
